version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"  # Location of package.json
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 99
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    commit-message:
      prefix: "chore"
      include: "scope"
